### ISSUE TITLE
Issue after update to Swift 3.1 and XCode 8.3

### ISSUE THREAD

**Issue by edumarket** [marcbaldwin/GestureRecognizerClosures#10]
Issue in calling convenience init of super class in

public extension UITapGestureRecognizer {

    /**
        Initializes a touch gesture-recognizer with the specificed number of taps, touches and handler
     */
    public convenience init(taps: Int = 1, touches: Int = 1, handler: @escaping (UITapGestureRecognizer) -> Void) {
        self.init(handler: handler, type: UITapGestureRecognizer.self)
        numberOfTapsRequired = taps
        numberOfTouchesRequired = touches
    }
}
**Argument labels '(handler:, type:)' do not match any available overloads**

**Comment by nttra83** [comment]
Hello @edumarket 
About this issue, you can do something like below:

/**
        Initializes a touch gesture-recognizer with the specificed number of taps, touches and handler
     */
    public convenience init(taps: Int = 1, touches: Int = 1, handler: @escaping (UITapGestureRecognizer) -> Void) {
        self.init(handler: handler)
        //self.init(handler: handler, type: UITapGestureRecognizer.self)
        numberOfTapsRequired = taps
        numberOfTouchesRequired = touches
    }

**Comment by edumarket** [comment]
@nttra83 no, it will not solve issue.
Issue is with accessing convenience init of the super class. Your fix will bring you error in runtime

**Comment by nttra83** [comment]
@edumarket 
Yes, I faced this issue in Xcode 8.3 :). You can fix it like me :).
Let me know if you face this issue again.

**Comment by edumarket** [comment]
It not works - in runtime EXC_BAD_ACCESS

**Comment by marcbaldwin** [comment]
@edumarket @nttra83 if you have a fix then please submit a pull request 👍  I'll take a look at the issue myself later today. Thanks :)

**Comment by edumarket** [comment]
As temporary solution i've remove extension of UIGestureRecognizer class and add extension with inits with closure into each GestureRecognizer class
It works, but looks ugly.
I can't understand why compiler cant build this thread of init calls

**Comment by edumarket** [comment]
i.e.
public extension UITapGestureRecognizer {

    /**
        Initializes a touch gesture-recognizer with the specificed number of taps, touches and handler
     */

    public convenience init(taps: Int = 1, touches: Int = 1, handler: @escaping (UITapGestureRecognizer) -> Void) {
        let handler = ClosureHandler<UITapGestureRecognizer>(handler: handler)
        self.init(target: handler, action: ClosureHandlerSelector)
        handler.control = (self)
        setHandler(handler)
        numberOfTapsRequired = taps
        numberOfTouchesRequired = touches
        
    }

**Comment by marcbaldwin** [comment]
This has been fixed thanks to @lucmirego  #11 

@edumarket @nttra83 please update your podfile as appropriate and run `pod update`
